-- Tabel untuk menyimpan data menu restoran
CREATE TABLE public.menu (
  id bigint generated by default as identity primary key,
  nama text not null,
  harga integer not null,
  kategori text not null,
  deskripsi text,
  bestseller boolean default false,
  emoji text,
  image_url text
);

-- Tabel untuk menyimpan data reservasi
CREATE TABLE public.reservations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  date date not null,
  time time not null,
  guests integer not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Memberikan akses baca untuk publik pada tabel menu (opsional, tergantung RLS)
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Menu is viewable by everyone" ON public.menu FOR SELECT USING (true);
-- Jika admin di sisi frontend hanya perlu API anon key tanpa login tambahan, kita bisa buka akses INSERT/UPDATE sementara:
CREATE POLICY "Menu can be edited by anon" ON public.menu FOR ALL USING (true);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Reservations are viewable by everyone" ON public.reservations FOR SELECT USING (true);
CREATE POLICY "Reservations can be edited by anon" ON public.reservations FOR ALL USING (true);
